ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'spec_helper'
require 'rspec/rails'
require 'capybara/rails'
require 'capybara/rspec'
require 'capybara/dsl'
require 'vcr'
require 'webmock'

ActiveRecord::Migration.maintain_test_schema!

RSpec.configure do |config|
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = true
  config.infer_spec_type_from_file_location!
  config.filter_rails_from_backtrace!
  config.fail_fast = true
  config.use_instantiated_fixtures = false
  config.include(Capybara, :type => :integration)
end

VCR.configure do |config|
  config.allow_http_connections_when_no_cassette = true
  config.cassette_library_dir = "spec/fixtures/vcr_cassettes"
  config.hook_into :webmock # or :fakeweb
end

def data_mock
  {
  "latitude": 39.7312095,
  "longitude": -104.9826965,
  "precision": {
    "name": "postal_code",
    "types": [
      "postal_code"
    ],
    "value": 5
  },
  "station_locator_url": "http://www.afdc.energy.gov/afdc/locator/stations/",
  "total_results": 67,
  "station_counts": {
    "total": 132,
    "fuels": {
      "HY": {
        "total": 0
      },
      "LNG": {
        "total": 0
      },
      "BD": {
        "total": 0
      },
      "CNG": {
        "total": 0
      },
      "LPG": {
        "total": 8
      },
      "E85": {
        "total": 0
      },
      "ELEC": {
        "total": 124,
        "stations": {
          "total": 59
        }
      }
    }
  },
  "offset": 0,
  "fuel_stations": [
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 66897,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "UDR",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:20:00Z",
      "geocode_status": "GPS",
      "latitude": 39.7300224,
      "longitude": -104.9883424,
      "city": "Denver",
      "intersection_directions": "816 ACOMA 1; For residents only - 5th Floor",
      "plus4": nil,
      "state": "CO",
      "street_address": "800 Acoma St",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:118249"
        ]
      },
      "distance": 0.3117
    },
    {
      "access_days_time": "Garage business hours; pay lot",
      "cards_accepted": nil,
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 50065,
      "groups_with_access_code": "Public",
      "open_date": "2012-12-01",
      "owner_type_code": "LG",
      "status_code": "E",
      "station_name": "City of Denver - Cultural Center Complex Garage",
      "station_phone": "303-640-1096",
      "updated_at": "2016-10-11T13:57:45Z",
      "geocode_status": "200-8",
      "latitude": 39.735271,
      "longitude": -104.9885199,
      "city": "Denver",
      "intersection_directions": "Located on level 3 by the elevator",
      "plus4": nil,
      "state": "CO",
      "street_address": "65 W 12th Ave",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772",
        "CHADEMO"
      ],
      "ev_dc_fast_num": 1,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 0.41801
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 75910,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "JOULE",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:00:03Z",
      "geocode_status": "GPS",
      "latitude": 39.7325011,
      "longitude": -104.9918712,
      "city": "Denver",
      "intersection_directions": "LEVEL 1; Garage entrance, residents and guests only",
      "plus4": nil,
      "state": "CO",
      "street_address": "1000 Speer Blvd",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:150057"
        ]
      },
      "distance": 0.49678
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 75913,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "JOULE",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:00:25Z",
      "geocode_status": "GPS",
      "latitude": 39.7325675,
      "longitude": -104.9918917,
      "city": "Denver",
      "intersection_directions": "LEVEL 2; Floor 2, residents and guests only",
      "plus4": nil,
      "state": "CO",
      "street_address": "1000 Speer",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:149247"
        ]
      },
      "distance": 0.49869
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 62140,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "CADACHARGEPOINT",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:37:40Z",
      "geocode_status": "GPS",
      "latitude": 39.723392,
      "longitude": -104.9842797,
      "city": "Denver",
      "intersection_directions": "CADA CARPORT 1",
      "plus4": nil,
      "state": "CO",
      "street_address": "290 E Speer Blvd",
      "zip": "80203",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:102063"
        ]
      },
      "distance": 0.54589
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 53942,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "PUBLIC STATIONS",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:53:45Z",
      "geocode_status": "GPS",
      "latitude": 39.7376694,
      "longitude": -104.9904124,
      "city": "Denver",
      "intersection_directions": "BANNOCK LOT 1; -",
      "plus4": nil,
      "state": "CO",
      "street_address": "1345 Bannock St",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:74433"
        ]
      },
      "distance": 0.60625
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 65434,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "PUBLIC STATIONS",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:53:46Z",
      "geocode_status": "GPS",
      "latitude": 39.737921,
      "longitude": -104.9940067,
      "city": "Denver",
      "intersection_directions": "JUSTICE CENTER; Adjacent to space 32 on level 2",
      "plus4": nil,
      "state": "CO",
      "street_address": "1370 Elati St",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:74363"
        ]
      },
      "distance": 0.75983
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 53945,
      "groups_with_access_code": "Public",
      "open_date": "2013-06-01",
      "owner_type_code": "LG",
      "status_code": "E",
      "station_name": "City of Denver - Denver Justice Center Garage",
      "station_phone": "303-607-9093  720-913-1750",
      "updated_at": "2016-10-11T13:57:34Z",
      "geocode_status": "200-8",
      "latitude": 39.738334,
      "longitude": -104.9937917,
      "city": "Denver",
      "intersection_directions": "Level 2, at the top of the entrance ramp, SW corner",
      "plus4": nil,
      "state": "CO",
      "street_address": "490 W 14th Ave",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 0.76868
    },
    {
      "access_days_time": "24 hours daily; pay lot",
      "cards_accepted": nil,
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 43833,
      "groups_with_access_code": "Public",
      "open_date": "2011-02-28",
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "Tremont Street Garage",
      "station_phone": "303-534-7559",
      "updated_at": "2016-01-13T18:00:17Z",
      "geocode_status": "200-8",
      "latitude": 39.742113,
      "longitude": -104.991416,
      "city": "Denver",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "400 15th St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "NEMA515",
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": 2,
      "ev_level2_evse_num": 2,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 0.88406
    },
    {
      "access_days_time": "24 hours daily; pay lot",
      "cards_accepted": nil,
      "date_last_confirmed": "2015-12-02",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 36353,
      "groups_with_access_code": "Public",
      "open_date": "2010-03-15",
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "Hyatt Regency Denver",
      "station_phone": "303-486-4467",
      "updated_at": "2016-01-13T18:00:43Z",
      "geocode_status": "200-8",
      "latitude": 39.7439318,
      "longitude": -104.992985,
      "city": "Denver",
      "intersection_directions": "At Colorado Convention Center, level 2",
      "plus4": nil,
      "state": "CO",
      "street_address": "650 15th St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "NEMA520"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": 4,
      "ev_level2_evse_num": nil,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 1.03475
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 53944,
      "groups_with_access_code": "Public",
      "open_date": "2013-06-01",
      "owner_type_code": "LG",
      "status_code": "E",
      "station_name": "City of Denver - Colorado Convention Center Garage",
      "station_phone": "303-228-8071  720-913-1750",
      "updated_at": "2016-10-11T13:57:36Z",
      "geocode_status": "GPS",
      "latitude": 39.742308,
      "longitude": -104.997556,
      "city": "Denver",
      "intersection_directions": "Parking space 1081. Level P-1, half way down the level near the freight elevator",
      "plus4": nil,
      "state": "CO",
      "street_address": "1104 Champa St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 1.10124
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 65432,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "PUBLIC STATIONS",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:53:49Z",
      "geocode_status": "GPS",
      "latitude": 39.7431367,
      "longitude": -104.9974677,
      "city": "Denver",
      "intersection_directions": "CONVENTION CTR; Enter garage off Speer before Champa. Located in space 1081 on Level 1",
      "plus4": nil,
      "state": "CO",
      "street_address": "1286-1296 Stout St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:74153"
        ]
      },
      "distance": 1.13847
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 65578,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "SPIRE",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:27:47Z",
      "geocode_status": "GPS",
      "latitude": 39.7448438,
      "longitude": -104.9958538,
      "city": "Denver",
      "intersection_directions": "PORTE COCHERE; Located in the Spire porte cochere off Champa. Available to the public while charging a vehicle at $5 per hour.  Registered resident rate is $2 per hour.",
      "plus4": nil,
      "state": "CO",
      "street_address": "891 14th St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:113141"
        ]
      },
      "distance": 1.173
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 65319,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "BROOKFIELD WEST",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:34:05Z",
      "geocode_status": "GPS",
      "latitude": 39.7477036,
      "longitude": -104.9897862,
      "city": "Denver",
      "intersection_directions": "1801 CAL 01; -",
      "plus4": nil,
      "state": "CO",
      "street_address": "1801 California St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:107401"
        ]
      },
      "distance": 1.19896
    },
    {
      "access_days_time": "24 hours daily; pay lot",
      "cards_accepted": nil,
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 50066,
      "groups_with_access_code": "Public",
      "open_date": "2012-12-01",
      "owner_type_code": "LG",
      "status_code": "E",
      "station_name": "City of Denver - Denver Performing Arts Center Garage",
      "station_phone": "303-607-9093  720-913-1750",
      "updated_at": "2016-10-11T13:58:43Z",
      "geocode_status": "GPS",
      "latitude": 39.743919,
      "longitude": -104.998075,
      "city": "Denver",
      "intersection_directions": "Located on level 4 by the elevators",
      "plus4": nil,
      "state": "CO",
      "street_address": "1055 13th St",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772",
        "CHADEMO"
      ],
      "ev_dc_fast_num": 1,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 1.19991
    },
    {
      "access_days_time": "MO: Not Specified; TU: Not Specified; WE: Not Specified; TH: Not Specified; FR: Not Specified; SA: Not Specified; SU: Not Specified",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 43406,
      "groups_with_access_code": "Public - Card key at all times",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "Walgreens - Denver, CO #1769",
      "station_phone": "800-663-5633",
      "updated_at": "2016-10-19T07:45:05Z",
      "geocode_status": "GPS",
      "latitude": 39.7398648,
      "longitude": -104.9630232,
      "city": "Denver",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "2000 E Colfax",
      "zip": "80206",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "SemaCharge Network",
      "ev_network_web": "http://www.semacharge.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "station": [
          "167"
        ],
        "posts": [
          "339"
        ]
      },
      "distance": 1.2061
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 78944,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "1",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T07:58:49Z",
      "geocode_status": "GPS",
      "latitude": 39.7495876,
      "longitude": -104.9803625,
      "city": "Denver",
      "intersection_directions": "PANA DENVER HQ2; West side of the building\nPANA DENVER HQ1; West side of the building",
      "plus4": nil,
      "state": "CO",
      "street_address": "6144 N. Panasonic Way",
      "zip": "80220",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 4,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:153249",
          "1:152557"
        ]
      },
      "distance": 1.274
    },
    {
      "access_days_time": "24 hours daily; for patron use only; see valet for access",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-05-09",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 70744,
      "groups_with_access_code": "Public",
      "open_date": "2015-10-01",
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "Four Seasons Hotel Denver",
      "station_phone": "303-389-3000  877-798-3752",
      "updated_at": "2016-05-09T14:41:46Z",
      "geocode_status": "200-8",
      "latitude": 39.7465555,
      "longitude": -104.9980168,
      "city": "Denver",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "1111 14th St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "TESLA",
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 4,
      "ev_network": "Tesla",
      "ev_network_web": "http://www.teslamotors.com/supercharger",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 1.3367
    },
    {
      "access_days_time": "MO: 12:00am-12:00am; TU: 12:00am-12:00am; WE: 12:00am-12:00am; TH: 12:00am-12:00am; FR: 12:00am-12:00am; SA: 12:00am-12:00am; SU: 12:00am-12:00am",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 72629,
      "groups_with_access_code": "Public - Card key at all times",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "1001 - 17th Street",
      "station_phone": "800-663-5633",
      "updated_at": "2016-10-19T07:46:56Z",
      "geocode_status": "GPS",
      "latitude": 39.7487525,
      "longitude": -104.9937407,
      "city": "Denver",
      "intersection_directions": "Stations are located on P1 Level",
      "plus4": nil,
      "state": "CO",
      "street_address": "1001 - 17th Street",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "SemaCharge Network",
      "ev_network_web": "http://www.semacharge.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "station": [
          "1300"
        ],
        "posts": [
          "3239"
        ]
      },
      "distance": 1.34568
    },
    {
      "access_days_time": "24 hours daily; for Tesla use only; see valet for access",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-09-02",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 77499,
      "groups_with_access_code": "Public",
      "open_date": "2016-07-15",
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "The Ritz-Carlton - Tesla",
      "station_phone": "303-312-3800  877-798-3789",
      "updated_at": "2016-09-02T17:58:10Z",
      "geocode_status": "200-8",
      "latitude": 39.7499978,
      "longitude": -104.9919883,
      "city": "Denver ",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "1881 Curtis St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "TESLA"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "Tesla",
      "ev_network_web": "http://www.teslamotors.com/supercharger",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 1.38748
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 61062,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "PARKING LEVEL 1",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:40:58Z",
      "geocode_status": "GPS",
      "latitude": 39.7480608,
      "longitude": -104.9974083,
      "city": "Denver",
      "intersection_directions": "WRITER SQUARE 1; Parking level P1 near elevators and cashier",
      "plus4": nil,
      "state": "CO",
      "street_address": "1501-1599 Lawrence St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:98225"
        ]
      },
      "distance": 1.402
    },
    {
      "access_days_time": "MO: Not Specified; TU: Not Specified; WE: Not Specified; TH: Not Specified; FR: Not Specified; SA: Not Specified; SU: Not Specified",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 68589,
      "groups_with_access_code": "Public - Card key at all times",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "Seventeenth Street Plaza",
      "station_phone": "800-663-5633",
      "updated_at": "2016-10-19T07:46:35Z",
      "geocode_status": "GPS",
      "latitude": 39.7501605,
      "longitude": -104.9951224,
      "city": "Denver",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "1225 17th St.",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "SemaCharge Network",
      "ev_network_web": "http://www.semacharge.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "station": [
          "1114"
        ],
        "posts": [
          "2643",
          "2642"
        ]
      },
      "distance": 1.4654
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 53941,
      "groups_with_access_code": "Public",
      "open_date": "2013-06-01",
      "owner_type_code": "LG",
      "status_code": "E",
      "station_name": "City of Denver - Acme Parking Lot",
      "station_phone": "303-607-9093  720-913-1750",
      "updated_at": "2016-10-11T13:57:47Z",
      "geocode_status": "200-8",
      "latitude": 39.7481076,
      "longitude": -105.0008461,
      "city": "Denver",
      "intersection_directions": "Located in the Northwest corner of the lot",
      "plus4": nil,
      "state": "CO",
      "street_address": "1430 14th St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 1.51446
    },
    {
      "access_days_time": "MO: 12:00am-12:00am; TU: 12:00am-12:00am; WE: 12:00am-12:00am; TH: 12:00am-12:00am; FR: 12:00am-12:00am; SA: 12:00am-12:00am; SU: 12:00am-12:00am",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 67673,
      "groups_with_access_code": "Public - Card key at all times",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "1800 Larimer",
      "station_phone": "800-663-5633",
      "updated_at": "2016-10-19T07:46:27Z",
      "geocode_status": "GPS",
      "latitude": 39.7512822,
      "longitude": -104.9944365,
      "city": "Denver",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "1800 Larimer Street, Suite 1800",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "SemaCharge Network",
      "ev_network_web": "http://www.semacharge.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "station": [
          "1036"
        ],
        "posts": [
          "2391",
          "2392"
        ]
      },
      "distance": 1.51945
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 65755,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "PUBLIC STATIONS",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:53:48Z",
      "geocode_status": "GPS",
      "latitude": 39.7479116,
      "longitude": -105.0021359,
      "city": "Denver",
      "intersection_directions": "FIREHOUSE 1; Enter parking lot near firehouse on 14th Court between Market and Blake. Station in south corner facing Auraria Campus",
      "plus4": nil,
      "state": "CO",
      "street_address": "1401 W 13th Ave",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:74163"
        ]
      },
      "distance": 1.54913
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 53946,
      "groups_with_access_code": "Public",
      "open_date": "2013-06-01",
      "owner_type_code": "LG",
      "status_code": "E",
      "station_name": "City of Denver - Firehouse Parking Lot",
      "station_phone": "303-607-9093  720-913-1750",
      "updated_at": "2016-10-11T13:57:49Z",
      "geocode_status": "200-8",
      "latitude": 39.748136,
      "longitude": -105.001953,
      "city": "Denver",
      "intersection_directions": "Located in the Southwest corner of the lot",
      "plus4": nil,
      "state": "CO",
      "street_address": "1322 Blake St",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 1.55423
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 69145,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "MONOGRAM RES",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:34:53Z",
      "geocode_status": "GPS",
      "latitude": 39.753644,
      "longitude": -104.9902644,
      "city": "Denver",
      "intersection_directions": "POINT 21; The station is located in the parking garage",
      "plus4": nil,
      "state": "CO",
      "street_address": "2131 Lawrence St",
      "zip": "80205",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:106201"
        ]
      },
      "distance": 1.59939
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 69859,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "DENIZEN",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:13:27Z",
      "geocode_status": "GPS",
      "latitude": 39.7091904,
      "longitude": -104.9927649,
      "city": "Denver",
      "intersection_directions": "SOUTH GARAGE 1; For residents and guests only. Between spaces 61 & 62 in south building ",
      "plus4": nil,
      "state": "CO",
      "street_address": "401-411 S Cherokee St",
      "zip": "80223",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:121905"
        ]
      },
      "distance": 1.61103
    },
    {
      "access_days_time": "MON: 24 hours | TUE: 24 hours | WED: 24 hours | THU: 24 hours | FRI: 24 hours | SAT: 24 hours | SUN: 24 hours",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 68434,
      "groups_with_access_code": "Private",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "Janus Capital Group",
      "station_phone": "888-998-2546",
      "updated_at": "2016-10-19T07:12:59Z",
      "geocode_status": "GPS",
      "latitude": 39.718799,
      "longitude": -104.956794,
      "city": "Denver",
      "intersection_directions": "Janus Capital employees & visitors only.\n",
      "plus4": nil,
      "state": "CO",
      "street_address": "151 Detroit Street",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "Blink Network",
      "ev_network_web": "http://www.blinknetwork.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "station": [
          "223880"
        ],
        "posts": [
          "50863"
        ]
      },
      "distance": 1.62396
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 67995,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "PUBLIC STATIONS",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:19:33Z",
      "geocode_status": "GPS",
      "latitude": 39.7497929,
      "longitude": -105.0038734,
      "city": "Denver",
      "intersection_directions": "ACME LOT 1; Enter lot from 14th St. & Wazee",
      "plus4": nil,
      "state": "CO",
      "street_address": "1700 14th St.",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:118425"
        ]
      },
      "distance": 1.70761
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 65756,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "PUBLIC STATIONS",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:53:46Z",
      "geocode_status": "GPS",
      "latitude": 39.7211042,
      "longitude": -104.9527601,
      "city": "Denver",
      "intersection_directions": "CH CRK LIBRARY; On alley side of library parking lot",
      "plus4": nil,
      "state": "CO",
      "street_address": "2951-2985 E 3rd Ave",
      "zip": "80206",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:74423"
        ]
      },
      "distance": 1.74052
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 65780,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "R8STATION 1",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:39:47Z",
      "geocode_status": "GPS",
      "latitude": 39.7518717,
      "longitude": -105.0015719,
      "city": "Denver",
      "intersection_directions": "EPA_STATION1",
      "plus4": nil,
      "state": "CO",
      "street_address": "1595 Wynkoop St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:99277"
        ]
      },
      "distance": 1.74434
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 53943,
      "groups_with_access_code": "Public",
      "open_date": "2013-06-01",
      "owner_type_code": "LG",
      "status_code": "E",
      "station_name": "City of Denver - Cherry Creek Branch Library Parking Lot",
      "station_phone": "720-913-1750",
      "updated_at": "2016-10-11T13:57:38Z",
      "geocode_status": "200-8",
      "latitude": 39.721257,
      "longitude": -104.952556,
      "city": "Denver",
      "intersection_directions": "Located near the exit of the parking lot, at Milwaukee St.",
      "plus4": nil,
      "state": "CO",
      "street_address": "305 Milwaukee St",
      "zip": "80206",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 1.74631
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 63109,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "VERVE DENVER",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:46:52Z",
      "geocode_status": "200-8",
      "latitude": 39.751747,
      "longitude": -105.004007,
      "city": "Denver",
      "intersection_directions": "VERVE P2 #2; For residents and guests only.\nVERVE P2 #1; For residents and guests only.",
      "plus4": nil,
      "state": "CO",
      "street_address": "1820 15th St",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 4,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:92317",
          "1:96723"
        ]
      },
      "distance": 1.81545
    },
    {
      "access_days_time": "7am-7pm M-Th and Sat, 7am-8pm F, 9am-5pm Sun",
      "cards_accepted": "Cash A D M V",
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "LPG",
      "id": 43883,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "U-Haul",
      "station_phone": "303-534-6072",
      "updated_at": "2016-10-17T20:07:15Z",
      "geocode_status": "200-8",
      "latitude": 39.7398141,
      "longitude": -105.0159387,
      "city": "Denver",
      "intersection_directions": "At Zuni, north of 14th St",
      "plus4": nil,
      "state": "CO",
      "street_address": "2000 W Lower Colfax Ave",
      "zip": "80204",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": nil,
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": nil,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": false,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 1.86752
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 62563,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "ROCKIES PARKING",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:42:03Z",
      "geocode_status": "200-8",
      "latitude": 39.7598137,
      "longitude": -104.9876131,
      "city": "Denver",
      "intersection_directions": "GARAGE FL 1 #2; 1st Floor on side facing ballpark\nGARAGE FL 1 #1; 1st Floor of garage, side closest to ballpark",
      "plus4": nil,
      "state": "CO",
      "street_address": "2722-2900 Broadway",
      "zip": "80205",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 4,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:96669",
          "1:98179"
        ]
      },
      "distance": 1.99072
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 66512,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "ALTA CITY HOUSE",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:33:44Z",
      "geocode_status": "200-9",
      "latitude": 39.7565853,
      "longitude": -105.0009206,
      "city": "Denver",
      "intersection_directions": "CITY HOUSE FL 4; Between spaces 286 and 287 on 4th floor\nCITY HOUSE FL 2; 2nd Floor\nCITY HOUSE FL 1; Between spaces 41 and 42 on 1st Floor\nCITY HOUSE FL 3; Between spaces 204 and 205 on 3rd floor\nCITY HOUSE FL 5; Between spaces 369 & 369 on 5th floor",
      "plus4": nil,
      "state": "CO",
      "street_address": "1801 Chestnut Place",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 10,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:107675",
          "1:107679",
          "1:107681",
          "1:107685",
          "1:107683"
        ]
      },
      "distance": 2.00175
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 67020,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "UDR",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:15:50Z",
      "geocode_status": "GPS",
      "latitude": 39.7173571,
      "longitude": -104.9495719,
      "city": "Denver",
      "intersection_directions": "STEELE CREEK 4A; For residents and guests only",
      "plus4": nil,
      "state": "CO",
      "street_address": "74-88 Steele St",
      "zip": "80206",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:120555"
        ]
      },
      "distance": 2.00685
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-04",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 76280,
      "groups_with_access_code": "Public",
      "open_date": "2016-06-01",
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "City of Denver - Chestnut Parking Lot",
      "station_phone": "303-607-9093",
      "updated_at": "2016-10-11T13:57:32Z",
      "geocode_status": "200-8",
      "latitude": 39.758012,
      "longitude": -104.9982284,
      "city": "Denver",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "2004 Chestnut Pl",
      "zip": "80202",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 2.02572
    },
    {
      "access_days_time": "7am-7pm M-Th and Sat, 7am-8pm F, 9am-5pm Sun",
      "cards_accepted": "Cash A D M V",
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "LPG",
      "id": 20343,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "U-Haul",
      "station_phone": "303-922-8225",
      "updated_at": "2016-10-13T19:02:48Z",
      "geocode_status": "200-8",
      "latitude": 39.7115269,
      "longitude": -105.01878,
      "city": "Denver",
      "intersection_directions": "West of I-25, at Conosa and Alameda",
      "plus4": nil,
      "state": "CO",
      "street_address": "2645 W Alameda Ave",
      "zip": "80219",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": nil,
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": nil,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": false,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 2.35362
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 74993,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "DMNS EVSE SYS",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T07:58:07Z",
      "geocode_status": "GPS",
      "latitude": 39.7490158,
      "longitude": -104.9438153,
      "city": "Denver",
      "intersection_directions": "DMNS EVES SYS; Located on the Parking Garage surface by the archway entrance",
      "plus4": nil,
      "state": "CO",
      "street_address": "2001 Colorado Blvd",
      "zip": "80205",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "NEMA520",
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": 1,
      "ev_level2_evse_num": 1,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:156053"
        ]
      },
      "distance": 2.40784
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 67328,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "RM",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:15:47Z",
      "geocode_status": "GPS",
      "latitude": 39.6961565,
      "longitude": -104.9795633,
      "city": "Denver",
      "intersection_directions": "WASH PARK 1; Northeast corner of building off Washington Street",
      "plus4": nil,
      "state": "CO",
      "street_address": "1101 S Washington St",
      "zip": "80210",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:120583"
        ]
      },
      "distance": 2.42407
    },
    {
      "access_days_time": "MO: Not Specified; TU: Not Specified; WE: Not Specified; TH: Not Specified; FR: Not Specified; SA: Not Specified; SU: Not Specified",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 78502,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "2785 Speer Apartments",
      "station_phone": "800-663-5633",
      "updated_at": "2016-10-19T07:47:20Z",
      "geocode_status": "GPS",
      "latitude": 39.7564541,
      "longitude": -105.0171538,
      "city": "Denver",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "2785 Speer Blvd.",
      "zip": "80211",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 4,
      "ev_network": "SemaCharge Network",
      "ev_network_web": "http://www.semacharge.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "station": [
          "1531"
        ],
        "posts": [
          "2249",
          "2250",
          "2248",
          "2251"
        ]
      },
      "distance": 2.53005
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 70717,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "KEW REALTY",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:10:00Z",
      "geocode_status": "GPS",
      "latitude": 39.7110993,
      "longitude": -104.9422169,
      "city": "Denver",
      "intersection_directions": "300 S JACKSON 1",
      "plus4": nil,
      "state": "CO",
      "street_address": "300 S Jackson St",
      "zip": "80209",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:124237"
        ]
      },
      "distance": 2.56435
    },
    {
      "access_days_time": "MO: Not Specified; TU: Not Specified; WE: Not Specified; TH: Not Specified; FR: Not Specified; SA: Not Specified; SU: Not Specified",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 43227,
      "groups_with_access_code": "Public - Card key at all times",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "Walgreens - Denver, CO #10935",
      "station_phone": "800-663-5633",
      "updated_at": "2016-10-19T07:45:03Z",
      "geocode_status": "GPS",
      "latitude": 39.7110482,
      "longitude": -105.0250667,
      "city": "Denver",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "300 S Federal Blvd",
      "zip": "80219",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "SemaCharge Network",
      "ev_network_web": "http://www.semacharge.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "station": [
          "155"
        ],
        "posts": [
          "727"
        ]
      },
      "distance": 2.65147
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 61641,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "BMW OF DENVER",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:43:35Z",
      "geocode_status": "200-9",
      "latitude": 39.6999357,
      "longitude": -104.9398757,
      "city": "Denver",
      "intersection_directions": "STATION 02\nSTATION 01",
      "plus4": nil,
      "state": "CO",
      "street_address": "900 S Colorado Blvd",
      "zip": "80246",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 4,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:95631",
          "1:95647"
        ]
      },
      "distance": 3.14015
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 65401,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "MURRAY BMW 1",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:35:50Z",
      "geocode_status": "200-8",
      "latitude": 39.699246,
      "longitude": -104.937633,
      "city": "Denver",
      "intersection_directions": "STATION SA02\nSTATION SA01",
      "plus4": nil,
      "state": "CO",
      "street_address": "4350 E Kentucky Ave",
      "zip": "80246",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:104329",
          "1:104363"
        ]
      },
      "distance": 3.26002
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 77940,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "UNIV OF DENVER",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:07:52Z",
      "geocode_status": "GPS",
      "latitude": 39.6799646,
      "longitude": -104.9639084,
      "city": "Denver",
      "intersection_directions": "STURM HALL 1",
      "plus4": nil,
      "state": "CO",
      "street_address": "2032-2054 S Race St",
      "zip": "80210",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:126445"
        ]
      },
      "distance": 3.67443
    },
    {
      "access_days_time": "MO: Not Specified; TU: Not Specified; WE: Not Specified; TH: Not Specified; FR: Not Specified; SA: Not Specified; SU: Not Specified",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 71281,
      "groups_with_access_code": "Public - Card key at all times",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "Walgreens - Denver, CO #6827",
      "station_phone": "800-663-5633",
      "updated_at": "2016-10-19T07:45:01Z",
      "geocode_status": "GPS",
      "latitude": 39.689069,
      "longitude": -105.025755,
      "city": "Denver",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "1505 S Federal Blvd",
      "zip": "80219",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 1,
      "ev_network": "SemaCharge Network",
      "ev_network_web": "http://www.semacharge.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "station": [
          "147"
        ],
        "posts": [
          "256"
        ]
      },
      "distance": 3.70357
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 76122,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "UNIV OF DENVER",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:00:41Z",
      "geocode_status": "GPS",
      "latitude": 39.6797519,
      "longitude": -104.9613496,
      "city": "Denver",
      "intersection_directions": "LAW GARAGE 1; Located near the elevators on P1",
      "plus4": nil,
      "state": "CO",
      "street_address": "2054-2062 S Gaylord St",
      "zip": "80210",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:148773"
        ]
      },
      "distance": 3.72787
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 76126,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "UNIV OF DENVER",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:04:26Z",
      "geocode_status": "GPS",
      "latitude": 39.6779646,
      "longitude": -104.9641587,
      "city": "Denver",
      "intersection_directions": "EVANS GARAGE 1; Located near the 2nd floor Stairs & Elevator",
      "plus4": nil,
      "state": "CO",
      "street_address": "1942-1998 Evans Ave",
      "zip": "80210",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:132203"
        ]
      },
      "distance": 3.80389
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 76125,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "UNIV OF DENVER",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:04:25Z",
      "geocode_status": "GPS",
      "latitude": 39.6737283,
      "longitude": -104.9601998,
      "city": "Denver",
      "intersection_directions": "P GARAGE 1; Near 2nd Floor ",
      "plus4": nil,
      "state": "CO",
      "street_address": "2300-2398 S York St",
      "zip": "80210",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:132235"
        ]
      },
      "distance": 4.14289
    },
    {
      "access_days_time": "8am-4:30pm M-F",
      "cards_accepted": "Cash A D M V",
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "LPG",
      "id": 15095,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "Suburban Propane",
      "station_phone": "303-232-1273",
      "updated_at": "2016-10-17T20:56:14Z",
      "geocode_status": "200-8",
      "latitude": 39.735907,
      "longitude": -105.060692,
      "city": "Lakewood",
      "intersection_directions": "I-25 to 6th Ave, west on Sheridan",
      "plus4": nil,
      "state": "CO",
      "street_address": "5725 W 11th Ave",
      "zip": "80214",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": nil,
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": nil,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": false,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 4.1672
    },
    {
      "access_days_time": "7am-7pm M-Th and Sat, 7am-8pm F, 9am-5pm Sun",
      "cards_accepted": "Cash A D M V",
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "LPG",
      "id": 70896,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "U-Haul",
      "station_phone": "303-936-2401",
      "updated_at": "2016-10-17T20:17:56Z",
      "geocode_status": "200-8",
      "latitude": 39.6966694,
      "longitude": -105.0527505,
      "city": "Lakewood",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "1104 S Sheridan Blvd",
      "zip": "80232",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": nil,
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": nil,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": false,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 4.42841
    },
    {
      "access_days_time": "7am-7pm M-Th and Sat, 7am-8pm F, 9am-5pm Sun",
      "cards_accepted": "Cash A D M V",
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "LPG",
      "id": 20342,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "U-Haul",
      "station_phone": "303-922-8186",
      "updated_at": "2016-10-17T20:44:32Z",
      "geocode_status": "200-8",
      "latitude": 39.6743774,
      "longitude": -105.024319,
      "city": "Denver",
      "intersection_directions": "South of Evans",
      "plus4": nil,
      "state": "CO",
      "street_address": "2322 S Federal Blvd",
      "zip": "80219",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": nil,
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": nil,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": false,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 4.50478
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2015-07-08",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 68154,
      "groups_with_access_code": "Public",
      "open_date": "2014-10-01",
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "Bubu Restaurant",
      "station_phone": "303-364-2025",
      "updated_at": "2016-01-13T17:53:05Z",
      "geocode_status": "200-8",
      "latitude": 39.7186469,
      "longitude": -104.8983346,
      "city": "Denver",
      "intersection_directions": nil,
      "plus4": nil,
      "state": "CO",
      "street_address": "4559 E Academy Blvd",
      "zip": "80230",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 4.57707
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 53078,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "IBEW68",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:48:01Z",
      "geocode_status": "GPS",
      "latitude": 39.7989545,
      "longitude": -104.9822851,
      "city": "Denver",
      "intersection_directions": "WIND TURBINE; Look for the Wind Turbine in Central parking lot and use parking spaces designated EV only",
      "plus4": nil,
      "state": "CO",
      "street_address": "5660 Logan St",
      "zip": "80216",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:90707"
        ]
      },
      "distance": 4.67384
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 66438,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "ADVENIR STAPLTN",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:27:18Z",
      "geocode_status": "GPS",
      "latitude": 39.7468486,
      "longitude": -104.8948523,
      "city": "Denver",
      "intersection_directions": "STAPLETON 1",
      "plus4": nil,
      "state": "CO",
      "street_address": "1955 Ulster St",
      "zip": "80220",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:113583"
        ]
      },
      "distance": 4.80161
    },
    {
      "access_days_time": "7am-7pm M-Th and Sat, 7am-8pm F, 9am-5pm Sun",
      "cards_accepted": "A Cash D M V",
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "LPG",
      "id": 20344,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "U-Haul",
      "station_phone": "303-399-7010",
      "updated_at": "2016-01-13T18:00:16Z",
      "geocode_status": "200-8",
      "latitude": 39.7397133,
      "longitude": -104.8932073,
      "city": "Denver",
      "intersection_directions": "At Unita",
      "plus4": nil,
      "state": "CO",
      "street_address": "8150 E Colfax Ave",
      "zip": "80220",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": nil,
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": nil,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": true,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 4.80265
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 78237,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "THE GROVE",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:09:57Z",
      "geocode_status": "GPS",
      "latitude": 39.7598071,
      "longitude": -104.8971994,
      "city": "Denver",
      "intersection_directions": "THE GROVE; -",
      "plus4": nil,
      "state": "CO",
      "street_address": "2980 Syracuse St",
      "zip": "80238",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:124257"
        ]
      },
      "distance": 4.96245
    },
    {
      "access_days_time": "7am-7pm M-Th and Sat, 7am-8pm F, 9am-5pm Sun",
      "cards_accepted": "Cash A D M V",
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "LPG",
      "id": 20341,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "U-Haul",
      "station_phone": "303-202-0686",
      "updated_at": "2016-10-17T20:25:41Z",
      "geocode_status": "GPS",
      "latitude": 39.72957,
      "longitude": -105.080944,
      "city": "Lakewood",
      "intersection_directions": "2 blocks north of 6th Ave",
      "plus4": nil,
      "state": "CO",
      "street_address": "830 Wadsworth Blvd",
      "zip": "80215",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": nil,
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": nil,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": false,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 5.2348
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 78841,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "MOLLYS",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T07:57:30Z",
      "geocode_status": "GPS",
      "latitude": 39.7788602,
      "longitude": -105.0598649,
      "city": "Denver",
      "intersection_directions": "STATION 1; West side of building",
      "plus4": nil,
      "state": "CO",
      "street_address": "5809 W 44th Ave",
      "zip": "80212",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:157851"
        ]
      },
      "distance": 5.26244
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 67681,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "RM",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:14:48Z",
      "geocode_status": "GPS",
      "latitude": 39.7090037,
      "longitude": -105.0805415,
      "city": "Lakewood",
      "intersection_directions": "BELMAR 1; Parking garage under Whole Foods Market, near W. Alaska Dr. entrance",
      "plus4": nil,
      "state": "CO",
      "street_address": "7444 W Alaska Dr",
      "zip": "80226",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:121187"
        ]
      },
      "distance": 5.43337
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 76274,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "DENVER RTD 1",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:04:48Z",
      "geocode_status": "GPS",
      "latitude": 39.7692927,
      "longitude": -104.8906523,
      "city": "Denver",
      "intersection_directions": "DENVER RTD 1; From the intersection of Uinta St and 37th Place, go east on 37th Place to the cul-de-sac. The charging station will be located 200 feet due north from the cul-de-sac.",
      "plus4": nil,
      "state": "CO",
      "street_address": "8200 Smith Rd",
      "zip": "80238",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:131459"
        ]
      },
      "distance": 5.56149
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 73325,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "ALTA CHERRY HLS",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:05:45Z",
      "geocode_status": "GPS",
      "latitude": 39.650637,
      "longitude": -104.9867066,
      "city": "Englewood",
      "intersection_directions": "WEST 1; For residents and guests only",
      "plus4": nil,
      "state": "CO",
      "street_address": "3601-3649 S Lincoln St",
      "zip": "80113",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:129437"
        ]
      },
      "distance": 5.56281
    },
    {
      "access_days_time": "7:30am-4:30pm M-F",
      "cards_accepted": "Cash Checks M V",
      "date_last_confirmed": "2015-11-03",
      "expected_date": nil,
      "fuel_type_code": "LPG",
      "id": 14525,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "Metrogas Inc",
      "station_phone": "303-428-3036",
      "updated_at": "2016-01-13T18:00:13Z",
      "geocode_status": "200-8",
      "latitude": 39.8127298,
      "longitude": -104.9961576,
      "city": "Denver",
      "intersection_directions": "At Huron St, driveway is between Broadway and Pecos",
      "plus4": nil,
      "state": "CO",
      "street_address": "790 W 64th Ave",
      "zip": "80221",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": nil,
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": nil,
      "ev_level2_evse_num": nil,
      "ev_network": nil,
      "ev_network_web": nil,
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": false,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "distance": 5.66964
    },
    {
      "access_days_time": "24 hours daily",
      "cards_accepted": nil,
      "date_last_confirmed": "2016-10-19",
      "expected_date": nil,
      "fuel_type_code": "ELEC",
      "id": 50753,
      "groups_with_access_code": "Public",
      "open_date": nil,
      "owner_type_code": nil,
      "status_code": "E",
      "station_name": "LAKEWOOD CO",
      "station_phone": "888-758-4389",
      "updated_at": "2016-10-19T08:51:31Z",
      "geocode_status": "GPS",
      "latitude": 39.7086498,
      "longitude": -105.085786,
      "city": "Lakewood",
      "intersection_directions": "CIVIC CENTER 1; Near the NW corner of the Cultural Center",
      "plus4": nil,
      "state": "CO",
      "street_address": "480 S Allison Pkwy",
      "zip": "80226",
      "bd_blends": nil,
      "e85_blender_pump": nil,
      "ev_connector_types": [
        "NEMA520",
        "J1772"
      ],
      "ev_dc_fast_num": nil,
      "ev_level1_evse_num": 1,
      "ev_level2_evse_num": 1,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": nil,
      "hy_status_link": nil,
      "lpg_primary": nil,
      "ng_fill_type_code": nil,
      "ng_psi": nil,
      "ng_vehicle_class": nil,
      "ev_network_ids": {
        "posts": [
          "1:86087"
        ]
      },
      "distance": 5.70861
    }
  ]
}
end
